export const BILLING_USAGE_COPY = {
  title: ["Ledger usage", { zh: "账本用量", ja: "帳簿の使用量", ko: "장부 사용량", fr: "Utilisation du registre", es: "Uso del libro" }],
  projects: ["Projects", { zh: "项目", ja: "プロジェクト", ko: "프로젝트", fr: "Projets", es: "Proyectos" }],
  expenseRecords: ["Expense records", { zh: "支出记录", ja: "支出記録", ko: "지출 기록", fr: "Enregistrements de dépenses", es: "Registros de gastos" }],
  used: ["Used", { zh: "已使用", ja: "使用済み", ko: "사용됨", fr: "Utilisé", es: "Usado" }],
  limit: ["Limit", { zh: "上限", ja: "上限", ko: "한도", fr: "Limite", es: "Límite" }],
  remaining: ["Remaining", { zh: "剩余", ja: "残り", ko: "남음", fr: "Restant", es: "Restante" }],
  reached: ["Limit reached", { zh: "已达到上限", ja: "上限に到達", ko: "한도 도달", fr: "Limite atteinte", es: "Límite alcanzado" }],
  over: ["Over limit by", { zh: "超出上限", ja: "上限超過", ko: "한도 초과", fr: "Dépassement de la limite", es: "Exceso sobre el límite" }],
  unavailable: ["Usage unavailable", { zh: "用量暂不可用", ja: "使用量を取得できません", ko: "사용량을 확인할 수 없습니다", fr: "Utilisation indisponible", es: "Uso no disponible" }],
  refresh: ["Refresh usage", { zh: "刷新用量", ja: "使用量を更新", ko: "사용량 새로고침", fr: "Actualiser l’utilisation", es: "Actualizar uso" }],
  scope: [
    "Usage is for the ledger you own, even when another ledger is selected. Members and API keys share this capacity.",
    {
      zh: "这里显示你拥有的账本用量，即使当前选择了其他账本。成员与 API 密钥共用这份容量。",
      ja: "別の帳簿を選択している場合も、ここにはあなたが所有する帳簿の使用量が表示されます。メンバーと API キーで容量を共有します。",
      ko: "다른 장부를 선택해도 여기에는 본인이 소유한 장부의 사용량이 표시됩니다. 구성원과 API 키는 이 용량을 공유합니다.",
      fr: "L’utilisation concerne le registre dont vous êtes propriétaire, même si un autre registre est sélectionné. Les membres et les clés API partagent cette capacité.",
      es: "El uso corresponde al libro que posees, aunque hayas seleccionado otro libro. Los miembros y las claves API comparten esta capacidad.",
    },
  ],
  retention: [
    "Archived or removed projects and removed expense records still count toward capacity. Expenses generated by recurring schedules count too. Capacity does not reset each month.",
    {
      zh: "归档或移除的项目、已移除的支出记录仍占用容量，周期计划生成的支出也计入用量。容量不会每月重置。",
      ja: "アーカイブ・削除済みのプロジェクトや削除済みの支出記録も容量に含まれます。定期支出で生成された記録も対象です。容量は毎月リセットされません。",
      ko: "보관하거나 제거한 프로젝트와 제거한 지출 기록도 용량에 포함됩니다. 반복 일정으로 생성된 지출도 포함되며 용량은 매월 초기화되지 않습니다.",
      fr: "Les projets archivés ou supprimés et les dépenses supprimées restent comptés. Les dépenses créées par les échéanciers récurrents comptent aussi. La capacité n’est pas réinitialisée chaque mois.",
      es: "Los proyectos archivados o eliminados y los registros de gastos eliminados siguen contando. También cuentan los gastos generados por programaciones recurrentes. La capacidad no se restablece cada mes.",
    },
  ],
  policy: [
    "Project and expense limits apply to the Owner’s ledger and are shared by members and API keys. Archived or removed projects and removed expense records still count toward capacity; it does not reset each month.",
    {
      zh: "项目和支出上限作用于 Owner 的账本，由成员及 API 密钥共用。归档或移除的项目、已移除的支出记录仍占用容量，容量不会每月重置。",
      ja: "プロジェクトと支出の上限は Owner の帳簿に適用され、メンバーと API キーで共有します。アーカイブ・削除済みのプロジェクトや削除済み支出も容量に含まれ、毎月リセットされません。",
      ko: "프로젝트와 지출 한도는 Owner의 장부에 적용되며 구성원과 API 키가 공유합니다. 보관하거나 제거한 프로젝트와 제거한 지출 기록도 용량에 포함되고 매월 초기화되지 않습니다.",
      fr: "Les limites de projets et de dépenses s’appliquent au registre de l’Owner et sont partagées par les membres et les clés API. Les projets archivés ou supprimés et les dépenses supprimées restent comptés ; la capacité n’est pas réinitialisée chaque mois.",
      es: "Los límites de proyectos y gastos se aplican al libro del Owner y se comparten entre miembros y claves API. Los proyectos archivados o eliminados y los registros de gastos eliminados siguen contando; la capacidad no se restablece cada mes.",
    },
  ],
};
