// Source-backed integration guidance in all supported languages.
export const DOCS_GUIDE = {
  projectSetup: [
    "In Projects, choose Add project, enter a name and optionally a description, then save. GitHub is optional for standalone projects. Connect GitHub only when you want to link up to 30 authorized repositories and a GitHub Organization. Changing these links preserves the project ID and expense history. GitHub access is checked for the acting member when linking repositories or adding expenses to a linked project.",
    {
      zh: "在项目页面点击“添加项目”，填写名称和可选说明后保存。独立项目无需 GitHub。需要关联仓库时再连接 GitHub，可关联最多 30 个已授权仓库及 GitHub 组织。修改关联会保留项目 ID 和历史支出。关联仓库或为已关联项目新增支出时，会检查当前操作成员的 GitHub 访问权。",
      ja: "プロジェクト画面で「プロジェクトを追加」を選び、名前と任意の説明を入力して保存します。独立したプロジェクトに GitHub は必須ではありません。最大 30 個の許可済みリポジトリと GitHub Organization を関連付ける場合だけ GitHub を接続します。関連付けを変更してもプロジェクト ID と支出履歴は保持されます。リポジトリの関連付けや関連付け済みプロジェクトへの支出追加では、操作するメンバーの GitHub アクセス権が確認されます。",
      ko: "프로젝트에서 프로젝트 추가를 선택하고 이름과 선택 사항인 설명을 입력한 후 저장하세요. 독립 프로젝트에는 GitHub가 필요하지 않습니다. 권한이 있는 저장소 최대 30개와 GitHub 조직을 연결하려는 경우에만 GitHub를 연결하세요. 연결을 변경해도 프로젝트 ID와 지출 내역은 유지됩니다. 저장소 연결이나 연결된 프로젝트의 지출 추가 시 작업하는 구성원의 GitHub 접근 권한을 확인합니다.",
      fr: "Dans Projets, choisissez Ajouter un projet, saisissez un nom et une description facultative, puis enregistrez. GitHub est facultatif pour les projets indépendants. Connectez GitHub uniquement pour associer jusqu’à 30 dépôts autorisés et une organisation GitHub. Modifier ces associations conserve l’ID du projet et l’historique des dépenses. L’accès GitHub du membre qui agit est vérifié lors de l’association de dépôts ou de l’ajout de dépenses à un projet associé.",
      es: "En Proyectos, elige Añadir proyecto, escribe un nombre y una descripción opcional y guarda. GitHub es opcional para los proyectos independientes. Conéctalo solo para vincular hasta 30 repositorios autorizados y una organización de GitHub. Cambiar estos vínculos conserva el ID del proyecto y su historial de gastos. Al vincular repositorios o añadir gastos a un proyecto vinculado, se comprueba el acceso a GitHub del miembro que realiza la acción.",
    },
  ],
  projectSettings: {
    id: "project-settings",
    title: [
      "Manage project settings",
      {
        zh: "管理项目设置",
        ja: "プロジェクト設定を管理",
        ko: "프로젝트 설정 관리",
        fr: "Gérer les paramètres du projet",
        es: "Gestionar la configuración del proyecto",
      },
    ],
    text: [
      "Open a project’s Project settings tab to edit its name, description, development and product links, GitHub associations or status. Links must use absolute HTTP(S) URLs; development links are manual shortcuts for standalone projects, while linked projects use currently authorized repository destinations. Owner and Admin manage project settings. Archived projects keep their recorded expenses in lists and reports but do not accept new expenses; set the status back to Active to use them again. Only the ledger Owner can permanently remove a project after confirmation. This deletes the project, expenses currently assigned to it, all its recurring schedules in every state and related business history. Expenses already moved to another project or the shared pool remain. This cannot be undone; Archive remains a separate action that preserves the project and its records.",
      {
        zh: "打开项目的“项目设置”，可修改名称、说明、开发和产品链接、GitHub 关联及状态。链接须为完整 HTTP(S) 网址；独立项目可填写开发快捷链接，已关联项目使用当前获准访问的仓库入口。Owner 和 Admin 可以管理项目设置。归档项目保留支出列表和报表中的已记录支出，但不能新增支出；将状态改回“启用”即可继续使用。只有账本 Owner 可以在确认后永久移除项目。此操作会删除项目、当前归属于它的支出、所有状态的周期计划及相关业务历史。已经移到其他项目或公共池的支出保留。此操作无法撤销；归档是独立操作，会保留项目及其记录。",
        ja: "プロジェクトの「プロジェクト設定」で名前、説明、開発・製品リンク、GitHub の関連付け、状態を編集できます。リンクには完全な HTTP(S) URL を使います。独立したプロジェクトでは開発リンクを手動で設定でき、関連付け済みプロジェクトでは現在アクセスできるリポジトリへのリンクを使います。Owner と Admin が設定を管理します。アーカイブしたプロジェクトの記録済み支出は一覧とレポートに残りますが、新しい支出は追加できません。状態を「有効」に戻すと再利用できます。プロジェクトの削除は帳簿の Owner だけが確認後に行えます。削除すると、プロジェクト、削除時点でそのプロジェクトに属する支出、状態を問わずすべての定期支出スケジュール、関連する業務履歴が完全に削除され、復元できません。すでに別のプロジェクトや共有プールへ移動した支出は残ります。アーカイブは別の操作で、プロジェクトと記録を保持します。",
        ko: "프로젝트의 프로젝트 설정 탭에서 이름, 설명, 개발 및 제품 링크, GitHub 연결과 상태를 수정하세요. 링크는 완전한 HTTP(S) URL이어야 합니다. 독립 프로젝트에는 개발 바로가기를 직접 입력할 수 있으며, 연결된 프로젝트는 현재 접근이 허용된 저장소 링크를 사용합니다. Owner와 Admin이 프로젝트 설정을 관리합니다. 보관된 프로젝트의 기존 지출은 목록과 보고서에 남지만 새 지출은 추가할 수 없습니다. 상태를 활성으로 되돌리면 다시 사용할 수 있습니다. 프로젝트 삭제는 장부 Owner만 확인 후 실행할 수 있습니다. 삭제하면 프로젝트, 삭제 시점에 해당 프로젝트에 속한 지출, 상태와 관계없이 모든 반복 일정, 관련 업무 기록이 영구 삭제되며 복원할 수 없습니다. 이미 다른 프로젝트나 공유 풀로 옮긴 지출은 유지됩니다. 보관은 프로젝트와 기록을 유지하는 별도 작업입니다.",
        fr: "Ouvrez l’onglet Paramètres du projet pour modifier son nom, sa description, ses liens de développement et de produit, ses associations GitHub ou son état. Utilisez des URL HTTP(S) absolues. Les projets indépendants permettent un raccourci de développement manuel ; les projets associés utilisent les dépôts actuellement autorisés. Owner et Admin gèrent ces paramètres. Un projet archivé conserve ses dépenses dans les listes et rapports, mais n’accepte plus de nouvelles dépenses ; remettez-le à Actif pour le réutiliser. Seul l’Owner du registre peut supprimer un projet, après confirmation. La suppression efface définitivement le projet, les dépenses qui lui sont rattachées au moment de la suppression, tous ses échéanciers récurrents quel que soit leur état et l’historique d’activité associé. Cette action est irréversible. Les dépenses déjà déplacées vers un autre projet ou le fonds partagé sont conservées. L’archivage reste une action distincte qui conserve le projet et ses enregistrements.",
        es: "Abre Configuración del proyecto para editar su nombre, descripción, enlaces de desarrollo y producto, vínculos con GitHub o estado. Los enlaces deben ser URL HTTP(S) absolutas. Los proyectos independientes admiten un acceso de desarrollo manual; los vinculados usan los repositorios autorizados actualmente. Owner y Admin gestionan la configuración. Los proyectos archivados conservan sus gastos en las listas e informes, pero no admiten gastos nuevos; vuelve al estado Activo para reutilizarlos. Solo el Owner del libro puede eliminar un proyecto, tras confirmarlo. La eliminación borra permanentemente el proyecto, los gastos que tenga asignados en ese momento, todas sus programaciones recurrentes independientemente de su estado y el historial de actividad relacionado. Esta acción es irreversible. Los gastos ya trasladados a otro proyecto o al fondo compartido se conservan. Archivar sigue siendo una acción distinta que conserva el proyecto y sus registros.",
      },
    ],
  },
  categories: [
    "In Categories, create a named category for the selected ledger. Owner and Admin can Rename with the pencil beside its title. Project and shared expenses use the same categories. Archive keeps a category in management and on historical records while preventing its selection for new expenses. Remove hides it from management and new choices, including Jev, even when saved records reference it. Historical expenses retain its name with a removed label. Editing an existing expense can keep its own original removed category or choose an active category; other expenses cannot newly use it. Removed categories cannot be renamed or restored. Schedules using one stop recording at their next due run; choose an active category and explicitly Resume the blocked schedule.",
    {
      zh: "在类别页面为当前账本创建有名称的类别。Owner 和 Admin 可点击名称旁的铅笔重命名，项目和公共池共用这些类别。归档后，类别仍保留在管理列表及历史记录中，但不能用于新支出。即使已被保存记录引用，也可以移除类别；移除后它不再出现在管理列表和新建选项中，Jev 也不能选择它。历史支出仍保留类别名称并标注已移除。编辑原支出时可以保留其原有的已移除类别，或选择启用类别；其他支出不能新分配该类别。已移除类别不能改名或恢复。使用它的周期计划从下一次到期执行起无法记录支出；请选择启用类别，并主动恢复被阻止的计划。",
      ja: "カテゴリー画面で現在の帳簿に名前付きカテゴリーを作成します。Owner と Admin は名前の横の鉛筆から名前を変更できます。プロジェクトと共有プールで同じカテゴリーを使います。アーカイブすると新しい支出には選択できなくなりますが、過去の記録には名前が残ります。使用済みのカテゴリーも削除できます。削除したカテゴリーは管理画面、新しい選択肢、Jev の提案に表示されなくなりますが、保存済み記録には名前と「削除済み」の表示が残ります。既存支出を編集するときは、その支出に元々設定されていた削除済みカテゴリーを維持するか、有効なカテゴリーを選べます。削除済みカテゴリーを新たに割り当てたり、名前を変更したり、復元したりすることはできません。そのカテゴリーを使う定期支出は次回の実行時にブロックされます。有効なカテゴリーを選び、明示的に「再開」してください。アーカイブは削除とは別の操作で、カテゴリーは管理画面と履歴に残ります。",
      ko: "카테고리에서 현재 장부의 이름 있는 카테고리를 만드세요. Owner와 Admin은 제목 옆 연필로 이름을 변경할 수 있습니다. 프로젝트와 공유 풀은 같은 카테고리를 사용합니다. 보관하면 새 지출에서 선택할 수 없지만 기존 기록의 이름은 유지됩니다. 이미 사용된 카테고리도 제거할 수 있습니다. 제거한 카테고리는 관리 화면, 새로 선택할 수 있는 항목과 Jev 제안에서 숨겨지지만 저장된 기록에는 이름과 '제거됨' 표시가 남습니다. 기존 지출을 수정할 때는 해당 지출에 원래 지정된 제거된 카테고리를 유지하거나 활성 카테고리를 선택할 수 있습니다. 제거한 카테고리를 새로 지정하거나 이름을 변경하거나 복원할 수는 없습니다. 해당 카테고리를 사용하는 반복 일정은 다음 실행 시점에 차단됩니다. 활성 카테고리를 선택하고 명시적으로 재개하세요. 보관은 제거와 별개의 작업이며 카테고리가 관리 화면과 내역에 남습니다.",
      fr: "Dans Catégories, créez une catégorie nommée pour le registre sélectionné. Owner et Admin peuvent la renommer avec le crayon à côté du titre. Les projets et le fonds partagé utilisent les mêmes catégories. Archiver empêche de choisir la catégorie pour de nouvelles dépenses, tout en conservant son nom dans l’historique. Vous pouvez aussi supprimer une catégorie déjà utilisée. Elle disparaît de la gestion des catégories, des nouveaux choix et des suggestions Jev, mais les enregistrements existants conservent son nom avec la mention « supprimée ». Lors de la modification d’une dépense existante, vous pouvez conserver sa catégorie supprimée d’origine ou choisir une catégorie active. Une catégorie supprimée ne peut plus être attribuée à une autre dépense, renommée ou restaurée. Les échéanciers qui l’utilisent sont bloqués à leur prochaine échéance : choisissez une catégorie active, puis reprenez-les explicitement. L’archivage reste une action distincte ; la catégorie reste visible dans la gestion des catégories et dans l’historique.",
      es: "En Categorías, crea una categoría con nombre para el libro seleccionado. Owner y Admin pueden renombrarla con el lápiz junto al título. Los proyectos y el fondo compartido usan las mismas categorías. Archivar impide elegirla para gastos nuevos y conserva su nombre en el historial. También puedes eliminar una categoría que ya esté en uso. Desaparece de la gestión de categorías, de las nuevas opciones y de las sugerencias de Jev, pero los registros guardados conservan su nombre con la etiqueta «eliminada». Al editar un gasto existente, puedes conservar la categoría eliminada que tenía originalmente o elegir una categoría activa. Una categoría eliminada no se puede asignar de nuevo, renombrar ni restaurar. Las programaciones que la usan se bloquean en su próxima ejecución: elige una categoría activa y pulsa Reanudar explícitamente. Archivar sigue siendo una acción distinta; la categoría permanece visible en la gestión de categorías y en el historial.",
    },
  ],
  expenses: [
    "Open a project or Shared Pool, choose Add expense and keep One-time selected. Enter the date, exact decimal amount, currency, category and purpose; note, quantity and unit are optional. The current page fixes the destination: a project expense stays in that project, and a shared expense stays in the shared pool. Use Edit or Remove on a saved row; removal requires confirmation. The shared pool is counted once in the ledger’s totals; it is not copied into every project. Web and REST API support creation, editing and removal for both destinations, with access controlled by your current role and key permissions.",
    {
      zh: "打开项目或公共池，点击“添加支出”并选择“单次”。填写日期、精确十进制金额、币种、类别和用途；备注、数量和单位可选。目标由当前页面固定：项目页面记入该项目，公共池页面记入公共池。在已保存记录上点击“编辑”或“移除”，移除需确认。公共池在账本总额中只计一次，不会复制到每个项目。Web 和 REST API 均支持两个目标的新增、编辑和移除，访问仍受当前角色与密钥权限限制。",
      ja: "プロジェクトまたは共有プールを開き、「支出を追加」で「単発」を選びます。日付、正確な十進数の金額、通貨、カテゴリー、用途を入力します。メモ、数量、単位は任意です。保存先は現在の画面で固定され、プロジェクト画面ではそのプロジェクト、共有プール画面では共有プールに記録されます。保存済み行の「編集」「削除」を使い、削除は確認後に実行します。共有プールは帳簿の合計に一度だけ計上され、各プロジェクトへ複製されません。Web と REST API は両方の保存先で追加、編集、削除に対応し、現在の役割とキーの権限が適用されます。",
      ko: "프로젝트 또는 공유 풀을 열고 지출 추가에서 일회를 선택하세요. 날짜, 정확한 십진 금액, 통화, 카테고리와 용도를 입력하세요. 메모, 수량과 단위는 선택 사항입니다. 대상은 현재 페이지로 고정됩니다. 프로젝트 지출은 해당 프로젝트에, 공유 지출은 공유 풀에 기록됩니다. 저장된 행에서 수정 또는 제거를 선택하며 제거는 확인이 필요합니다. 공유 풀은 장부 합계에 한 번만 포함되고 각 프로젝트에 복사되지 않습니다. Web과 REST API 모두 두 대상의 추가, 수정, 제거를 지원하며 현재 역할과 키 권한이 적용됩니다.",
      fr: "Ouvrez un projet ou le Fonds partagé, choisissez Ajouter une dépense et gardez Ponctuelle. Saisissez la date, le montant décimal exact, la devise, la catégorie et le motif ; note, quantité et unité sont facultatives. La page fixe la destination : le projet courant ou le fonds partagé. Utilisez Modifier ou Supprimer sur une ligne enregistrée ; la suppression demande confirmation. Le fonds partagé est compté une seule fois dans les totaux du registre, sans copie dans chaque projet. Le Web et l’API REST permettent de créer, modifier et supprimer dans les deux destinations, selon votre rôle actuel et les permissions de la clé.",
      es: "Abre un proyecto o el Fondo compartido, elige Añadir gasto y mantén Único. Introduce fecha, importe decimal exacto, moneda, categoría y motivo; nota, cantidad y unidad son opcionales. La página fija el destino: el proyecto actual o el fondo compartido. Usa Editar o Eliminar en una fila guardada; eliminar requiere confirmación. El fondo compartido se cuenta una sola vez en los totales del libro y no se copia en cada proyecto. La Web y la API REST permiten crear, editar y eliminar en ambos destinos según tu rol actual y los permisos de la clave.",
    },
  ],
  recurring: {
    id: "recurring",
    title: [
      "Manage recurring expenses",
      {
        zh: "管理周期支出",
        ja: "定期支出を管理",
        ko: "반복 지출 관리",
        fr: "Gérer les dépenses récurrentes",
        es: "Gestionar gastos recurrentes",
      },
    ],
    text: [
      "In a project or Shared Pool, choose Add expense, then Recurring. Enter an explicit active category and select weekly, monthly, quarterly or yearly. Set the start date, an IANA time zone such as Asia/Shanghai, and an optional inclusive end date. Weekly rules use a weekday; monthly rules use a day of month; quarterly rules also select the month within each calendar quarter; yearly rules also select a month of year. A day beyond the month’s length uses its last day. Save schedule creates a rule, not a payment; future occurrences do not count as spent until they become recorded expenses. The schedule list shows the next occurrence and status. Edit affects future occurrences only. Pause stops posting; Resume starts with future occurrences, and paused or blocked periods are not backfilled. Cancel permanently stops the rule while keeping already recorded expenses. Both project and shared-pool schedules support the same actions in Web and REST API.",
      {
        zh: "在项目或公共池点击“添加支出”，再选择“周期”。必须选择明确的启用类别，并设置每周、每月、每季度或每年。填写开始日期、Asia/Shanghai 等 IANA 时区，以及可选的结束日期（包含当天）。每周选择星期；每月选择日号；每季度还需选择自然季度中的第几个月；每年还需选择月份。日号超出当月天数时使用当月最后一天。“保存周期计划”创建的是记账规则，不会扣款；未来周期在实际生成支出前不计入已花费金额。计划列表展示下一次发生日期和状态。编辑仅影响未来周期；暂停会停止生成，恢复只从未来周期继续，不补记暂停或阻塞期间的支出。取消会永久停止规则，已经记入的支出仍保留。项目和公共池的周期计划在 Web 与 REST API 中支持相同操作。",
        ja: "プロジェクトまたは共有プールの「支出を追加」で「定期」を選びます。有効なカテゴリーを明示し、毎週、毎月、四半期ごと、毎年から選択します。開始日、Asia/Shanghai などの IANA タイムゾーン、任意の終了日（当日を含む）を設定します。毎週は曜日、毎月は日を選びます。四半期ごとは暦上の四半期内の月、毎年は年内の月も指定します。月の日数を超える日は月末に置き換えます。保存すると記帳ルールを作成し、支払いは行いません。将来の発生分は支出として記録されるまで合計に含まれません。一覧で次回発生日と状態を確認できます。編集は将来分だけに適用されます。一時停止すると記帳が止まり、再開は将来分から始まるため、停止・ブロック期間分は遡って記録されません。キャンセルはルールを永久に停止し、記録済み支出は保持します。プロジェクトと共有プールの定期支出は Web と REST API で同じ操作に対応します。",
        ko: "프로젝트 또는 공유 풀의 지출 추가에서 반복을 선택하세요. 활성 카테고리를 명시적으로 선택하고 매주, 매월, 분기별 또는 매년을 설정하세요. 시작일, Asia/Shanghai 같은 IANA 시간대와 선택 사항인 종료일을 입력하며 종료일도 포함됩니다. 매주는 요일, 매월은 일자를 선택합니다. 분기별은 달력 분기 내 월, 매년은 연중 월도 선택합니다. 일자가 월의 일수를 넘으면 말일을 사용합니다. 일정 저장은 기록 규칙을 만들며 결제를 실행하지 않습니다. 미래 발생분은 실제 지출로 기록되기 전까지 지출 합계에 포함되지 않습니다. 목록에서 다음 발생일과 상태를 확인하세요. 수정은 미래 발생분에만 적용됩니다. 일시 중지하면 기록이 멈추고 재개는 미래 발생분부터 시작하며 중지 또는 차단된 기간은 소급 기록되지 않습니다. 취소하면 규칙이 영구 중단되지만 이미 기록된 지출은 유지됩니다. 프로젝트와 공유 풀의 반복 일정은 Web과 REST API에서 같은 작업을 지원합니다.",
        fr: "Dans un projet ou le Fonds partagé, choisissez Ajouter une dépense, puis Récurrente. Sélectionnez explicitement une catégorie active et une fréquence hebdomadaire, mensuelle, trimestrielle ou annuelle. Définissez la date de début, un fuseau IANA comme Asia/Shanghai et une date de fin facultative, incluse. Choisissez un jour de semaine pour l’hebdomadaire et un jour du mois pour les autres fréquences ; précisez aussi le mois du trimestre civil ou de l’année selon le cas. Un jour dépassant la durée du mois devient son dernier jour. Enregistrer l’échéancier crée une règle, sans paiement ; les occurrences futures ne sont comptées qu’une fois enregistrées comme dépenses. La liste affiche la prochaine occurrence et l’état. Modifier ne change que les occurrences futures. Mettre en pause arrête la création ; reprendre repart des occurrences futures, sans rattraper les périodes en pause ou bloquées. Annuler arrête définitivement la règle et conserve les dépenses déjà enregistrées. Le Web et l’API REST offrent les mêmes actions pour les projets et le fonds partagé.",
        es: "En un proyecto o el Fondo compartido, elige Añadir gasto y después Recurrente. Selecciona explícitamente una categoría activa y una frecuencia semanal, mensual, trimestral o anual. Configura la fecha de inicio, una zona IANA como Asia/Shanghai y una fecha final opcional, incluida. La frecuencia semanal usa un día de la semana; las demás, un día del mes. La trimestral añade el mes dentro del trimestre natural y la anual, el mes del año. Si el día supera la duración del mes, se usa su último día. Guardar la programación crea una regla, sin realizar pagos; las ocurrencias futuras solo cuentan cuando se registran como gastos. La lista muestra la próxima ocurrencia y el estado. Editar afecta solo a ocurrencias futuras. Pausar detiene el registro; Reanudar parte de ocurrencias futuras, sin recuperar períodos pausados o bloqueados. Cancelar detiene la regla permanentemente y conserva los gastos ya registrados. La Web y la API REST ofrecen las mismas acciones para proyectos y el fondo compartido.",
      },
    ],
  },
  activity: {
    id: "activity",
    title: [
      "Read the operation log",
      {
        zh: "查看操作日志",
        ja: "操作ログを確認",
        ko: "작업 로그 보기",
        fr: "Consulter le journal des opérations",
        es: "Consultar el registro de operaciones",
      },
    ],
    text: [
      "Open Operation log in a project or Shared Pool to see changes from the last 24 hours: who acted, when, which record changed and its before-and-after values. The window follows Server time, and the newest events appear first. Load more reads the next page; Reload explicitly refreshes the log. The log loads when first opened and does not poll or replace the ledger’s retained history. API results follow the key’s current scopes and project/shared restrictions.",
      {
        zh: "打开项目或公共池的“操作日志”，查看最近 24 小时内的操作人、时间、受影响记录和修改前后值。时间窗口以服务端为准，最新事件排在最前。点击“加载更多”读取下一页，点击“重新加载”主动刷新。日志首次打开时加载，不会轮询，也不替代账本保留的历史。API 返回结果仍受密钥当前权限及项目和公共池限制约束。",
        ja: "プロジェクトまたは共有プールの「操作ログ」で、直近 24 時間の操作した人、時刻、対象の記録、変更前後の値を確認できます。期間はサーバー時刻に基づき、新しいイベントが先に表示されます。「さらに読み込む」は次のページを、「再読み込み」は最新のログを取得します。初めて開いたときに読み込まれ、定期取得は行いません。帳簿に保持された履歴を置き換えるものではありません。API の結果にはキーの現在のスコープとプロジェクト・共有プールの制限が適用されます。",
        ko: "프로젝트 또는 공유 풀의 작업 로그에서 최근 24시간의 작업자, 시간, 변경된 기록과 변경 전후 값을 확인하세요. 시간 범위는 서버 시간을 기준으로 하며 최신 이벤트가 먼저 표시됩니다. 더 불러오기는 다음 페이지를 읽고 새로고침은 로그를 명시적으로 갱신합니다. 처음 열 때 로드하며 주기적으로 조회하지 않고 장부에 보존된 내역을 대체하지 않습니다. API 결과에는 키의 현재 범위와 프로젝트 및 공유 풀 제한이 적용됩니다.",
        fr: "Ouvrez Journal des opérations dans un projet ou le Fonds partagé pour voir les dernières 24 heures : auteur, heure, enregistrement concerné et valeurs avant/après. La fenêtre suit l’heure du serveur et les événements les plus récents apparaissent d’abord. Charger plus lit la page suivante ; Recharger actualise explicitement le journal. Il se charge à la première ouverture, sans interrogation périodique, et ne remplace pas l’historique conservé du registre. Les résultats API respectent les permissions actuelles de la clé et ses restrictions de projets ou de fonds partagé.",
        es: "Abre Registro de operaciones en un proyecto o el Fondo compartido para ver las últimas 24 horas: quién actuó, cuándo, qué registro cambió y sus valores anteriores y posteriores. La ventana sigue la hora del servidor y los eventos más recientes aparecen primero. Cargar más lee la siguiente página; Recargar actualiza el registro explícitamente. Se carga al abrirlo por primera vez, sin consultas periódicas, y no sustituye el historial conservado del libro. Los resultados de la API respetan los permisos actuales de la clave y sus restricciones de proyectos y fondo compartido.",
      },
    ],
  },
  keys: [
    "In API Keys, name a key for the selected ledger, choose the scopes you need, then choose its project restrictions and explicitly allow the shared pool if required. Copy the token when it is created; it is shown only once. The REST API uses the same expense and recurring-rule endpoints for projects and the shared pool, with target selecting the destination. The API quickstart below shows the base URL, Bearer authentication, how to obtain project/category IDs, request and response bodies, and a first working call. Use Idempotency-Key for expense and schedule creation, and the latest quoted revision in If-Match for edits and removals. A key cannot exceed its issuer’s current role; a team membership revision change invalidates existing team keys. Revoking a key stops its access. REST member reads use members:read; governance writes require members:write and current Owner or Admin authority. Governance keys must omit projectIds. Owner project removal also requires projects:write and current target permission. Recurring keys use expenses:read/write and are rechecked at every occurrence; full edits or explicit Resume adopt the acting credential. Joining an invitation still uses the applicant's own signed-in account.",
    {
      zh: "在 API Keys 中为当前账本的密钥命名、选择所需权限，再设置项目限制并按需显式允许公共池。创建后立即复制令牌，令牌只显示一次。REST API 中项目和公共池共用支出与周期规则接口，通过 target 指定目标。下方 API 接入教程说明基础地址、Bearer 认证、项目和类别 ID 获取方式、请求与响应格式，并提供首次可运行调用。新增支出和周期计划使用 Idempotency-Key，编辑和移除使用带双引号的最新 revision 作为 If-Match。密钥不能超出发行者当前角色，团队成员权限版本变化后原密钥会失效，撤销后无法继续访问。 REST 成员读取使用 members:read；管理写入需要 members:write 及当前 Owner 或 Admin 权限，且不能设置 projectIds 限制。Owner 移除项目还需 projects:write 和当前目标权限。周期密钥使用 expenses:read/write，每次执行都重新校验；完整编辑或主动恢复会采用当前操作凭据。 通过邀请申请加入仍需申请人自己登录的账户。",
      ja: "API Keys で現在の帳簿のキーに名前を付け、必要なスコープ、プロジェクトの制限を選びます。共有プールが必要なら明示的に許可します。トークンは作成時に一度だけ表示されるため、その場でコピーしてください。REST API はプロジェクトと共有プールで同じ支出・定期ルールのエンドポイントを使い、target で保存先を指定します。下の API 導入ガイドに基本 URL、Bearer 認証、プロジェクトとカテゴリーの ID の取得方法、リクエスト・レスポンス、最初の実行例があります。支出と定期支出の作成には Idempotency-Key、編集・削除には最新 revision を二重引用符で囲んだ If-Match を使います。キーは発行者の現在の役割を超えられず、チームのメンバー権限のバージョン変更で既存キーは無効になります。取り消したキーはアクセスできません。 REST のメンバー読み取りは members:read、管理書き込みは members:write と現在の Owner または Admin 権限が必要です。管理キーでは projectIds を省略します。所有者によるプロジェクト削除にも projects:write と現在の対象権限が必要です。定期支出のキーは expenses:read/write を使い、各実行時に再確認されます。完全な編集や明示的な再開は現在の資格情報を採用します。 招待への参加申請には申請者自身のログインしたアカウントを使います。",
      ko: "API Keys에서 현재 장부의 키 이름을 정하고 필요한 범위와 프로젝트 제한을 선택하세요. 공유 풀이 필요하면 명시적으로 허용하세요. 토큰은 생성할 때 한 번만 표시되므로 즉시 복사하세요. REST API는 프로젝트와 공유 풀에 같은 지출 및 반복 규칙 엔드포인트를 사용하고 target으로 대상을 지정합니다. 아래 API 시작 안내에서 기본 URL, Bearer 인증, 프로젝트와 카테고리 ID 조회, 요청과 응답 형식, 처음 실행할 호출을 확인할 수 있습니다. 지출 및 일정 생성은 Idempotency-Key를, 수정과 제거는 최신 revision을 큰따옴표로 감싼 If-Match를 사용하세요. 키는 발급자의 현재 역할 권한을 넘을 수 없으며 팀 구성원 권한 버전이 바뀌면 기존 팀 키가 무효화됩니다. 취소한 키는 접근할 수 없습니다. REST 멤버 읽기는 members:read, 관리 쓰기는 members:write와 현재 Owner 또는 Admin 권한이 필요합니다. 관리 키에는 projectIds를 생략해야 합니다. 소유자의 프로젝트 삭제도 projects:write와 현재 대상 권한이 필요합니다. 반복 키는 expenses:read/write를 사용하며 매 실행마다 재검사되고 전체 수정·명시적 재개는 현재 자격 증명을 채택합니다. 초대 가입 신청은 신청자 자신의 로그인한 계정을 사용합니다.",
      fr: "Dans API Keys, nommez une clé pour le registre sélectionné, choisissez les permissions nécessaires, puis ses restrictions de projets et autorisez explicitement le fonds partagé si besoin. Copiez le jeton à sa création : il n’est affiché qu’une fois. L’API REST utilise les mêmes endpoints de dépenses et de règles récurrentes pour les projets et le fonds partagé, avec target pour choisir la destination. Le guide de démarrage ci-dessous indique l’URL de base, l’authentification Bearer, l’obtention des ID de projet et catégorie, les corps des requêtes et réponses et un premier appel exécutable. Utilisez Idempotency-Key pour créer une dépense ou un échéancier, et la dernière revision entre guillemets dans If-Match pour modifier ou supprimer. Une clé ne peut pas dépasser le rôle actuel de son auteur ; un changement de version d’adhésion invalide les clés d’équipe existantes. Révoquer une clé arrête son accès. Les lectures REST des membres utilisent members:read ; les opérations d’écriture de gestion exigent members:write et les droits actuels Owner ou Admin. Les clés de gestion doivent omettre projectIds. La suppression d’un projet par le propriétaire exige aussi projects:write et les droits actuels sur la cible. Les clés récurrentes utilisent expenses:read/write et sont revérifiées à chaque occurrence ; les modifications complètes et reprises explicites adoptent les identifiants utilisés pour l’action. Rejoindre via invitation utilise toujours le propre compte connecté du candidat.",
      es: "En API Keys, asigna un nombre a la clave del libro seleccionado, elige los permisos necesarios y las restricciones de proyectos y permite explícitamente el fondo compartido si lo necesitas. Copia el token al crearlo: solo se muestra una vez. La API REST usa los mismos endpoints de gastos y reglas recurrentes para proyectos y fondo compartido, con target para elegir el destino. La guía de inicio de abajo explica la URL base, autenticación Bearer, obtención de ID de proyecto y categoría, cuerpos de solicitud y respuesta y una primera llamada ejecutable. Usa Idempotency-Key para crear gastos y programaciones, y la última revision entre comillas en If-Match para editar y eliminar. Una clave no puede superar el rol actual de quien la creó; cambiar la versión de membresía invalida las claves de equipo existentes. Revocar una clave detiene su acceso. Las lecturas REST de miembros usan members:read; las operaciones de escritura de gestión exigen members:write y permisos actuales Owner o Admin. Las claves de gestión deben omitir projectIds. Eliminar proyectos como propietario también requiere projects:write y permisos actuales del destino. Las claves recurrentes usan expenses:read/write y se revisan en cada ejecución; editar completamente o reanudar explícitamente adopta la credencial actual. Solicitar entrada por invitación sigue usando la propia cuenta conectada del solicitante.",
    },
  ],
  membersManagement: [
    "To change a member’s role, unlock the role control, select an allowed role, and wait for the saved roster to reload; it locks again after success. Use Remove and confirm to revoke membership. The Owner cannot be changed or removed. Role changes and removal invalidate that member’s existing team keys. Use the join-request inbox or Members to review applicants; refresh manually when needed.",
    {
      zh: "修改成员角色时，先解锁角色控件，再选择可授予的角色；保存并重新读取成员列表后会自动锁定。点击“移除”并确认可撤销成员资格。Owner 不能修改或移除。角色变化和移除会使该成员原有团队密钥失效。可在加入申请收件箱或成员页面审批，按需主动刷新。",
      ja: "役割を変更するには役割のロックを解除し、許可された役割を選びます。保存後にメンバー一覧が再取得され、成功すると再びロックされます。「削除」を確認するとメンバー資格を取り消します。Owner は変更・削除できません。役割変更や削除でそのメンバーの既存チームキーは無効になります。参加申請の受信箱またはメンバー画面で申請を確認し、必要に応じて手動で更新してください。",
      ko: "구성원의 역할을 바꾸려면 역할 잠금을 해제하고 허용된 역할을 선택하세요. 저장된 구성원 목록이 다시 로드되면 성공 후 잠깁니다. 제거를 선택하고 확인하면 구성원 자격이 취소됩니다. Owner는 변경하거나 제거할 수 없습니다. 역할 변경과 제거는 해당 구성원의 기존 팀 키를 무효화합니다. 참여 신청 수신함이나 구성원에서 신청자를 검토하고 필요하면 수동으로 새로고침하세요.",
      fr: "Pour changer un rôle, déverrouillez le contrôle, choisissez un rôle autorisé et attendez le rechargement de la liste enregistrée ; il se verrouille à nouveau après succès. Utilisez Supprimer et confirmez pour révoquer l’adhésion. L’Owner ne peut être modifié ni supprimé. Les changements de rôle et suppressions invalident les clés d’équipe existantes du membre. Examinez les candidats dans la boîte des demandes ou Membres et actualisez manuellement si nécessaire.",
      es: "Para cambiar un rol, desbloquea el control, selecciona un rol permitido y espera a que se recargue la lista guardada; se bloqueará de nuevo tras guardar correctamente. Usa Eliminar y confirma para revocar la membresía. El Owner no se puede cambiar ni eliminar. Los cambios de rol y la eliminación invalidan las claves de equipo existentes del miembro. Revisa solicitantes en la bandeja de solicitudes o en Miembros y actualiza manualmente cuando sea necesario.",
    },
  ],
  quickstartLink: [
    "API quickstart",
    {
      zh: "API 接入教程",
      ja: "API 導入ガイド",
      ko: "API 시작 안내",
      fr: "Démarrage rapide de l’API",
      es: "Inicio rápido de la API",
    },
  ],
  expenseRetention: {
    id: "expense-retention",
    title: [
      "Expense capacity and automatic removal",
      {
        zh: "支出容量与自动移除",
        ja: "支出の容量と自動削除",
        ko: "지출 용량 및 자동 제거",
        fr: "Capacité des dépenses et suppression automatique",
        es: "Capacidad de gastos y eliminación automática",
      },
    ],
    text: [
      "In Settings, automatically removing the oldest expense is Off by default on every plan and adds no charges. The setting belongs to your own account, even when another shared ledger is selected; shared ledgers follow their own Owner's setting. Expense capacity counts undeleted shared-pool expenses and expenses in active or archived projects. Manually removing an expense, automatically removing it, or removing its project frees expense slots; archived and removed projects still count toward project capacity. Off blocks new expenses when full. Turn it On only if you agree to remove the oldest expense before saving a new one when exactly full. Oldest is ordered by expense date, then creation time, then ID, across that Owner's visible ledger. You must have permission to remove that exact expense; otherwise saving is blocked rather than skipping to a newer expense. Removed expenses disappear from ordinary expense reads, lists, reports and CSV and cannot be restored. Internal audit history remains; the authorized last-24-hour operation log can still show removal events and their changes. If usage exceeds a lowered plan limit, clear records manually first; the setting does not perform bulk cleanup. A failed save does not remove the old expense, and retrying the same successful request does not remove another one. Recurring generation follows the same setting. Changing the switch does not immediately remove expenses or reset usage.",
      {
        zh: "在设置中，“自动移除最早支出”在所有套餐下默认关闭，且不收取额外费用。偏好属于你自己的账户，即使当前选中其他共享账本也不改变；共享账本遵循其自身 Owner 的设置。支出容量统计未移除的公共池支出及启用或归档项目内的支出。手动或自动移除支出、移除其项目都会释放支出名额；归档和移除的项目仍占用项目容量。关闭时容量满后阻止新增。只有接受恰好满额时先移除最早一笔再保存新支出，才应开启。最早顺序按支出日期、创建时间、ID 依次判定，范围为该 Owner 的整个可见账本。你必须有权限移除这条确切记录，否则保存被阻止，不会跳过它改删较新记录。移除支出不再通过普通支出读取、列表、报表和 CSV 呈现，且无法恢复；内部审计历史仍保留，获授权的最近 24 小时操作日志仍可显示移除事件及其变更。降级后若使用量超过新上限，须先手动清理，设置不会批量移除。保存失败不移除旧支出，重试同一已成功请求不会再次移除。周期生成也遵循该设置。 切换开关不会立即移除支出或重置使用量。",
        ja: "設定の「最も古い支出を自動削除」は全プランで既定では Off で、追加料金はかかりません。他の共有帳簿を選んでいても自分のアカウントの設定を変更し、共有帳簿は自身の Owner の設定に従います。支出枠は未削除の共有プール支出と有効・アーカイブ済みプロジェクトの支出を数えます。支出の手動・自動削除やプロジェクト削除で支出枠が空きますが、アーカイブ・削除済みプロジェクトはプロジェクト枠を消費し続けます。Off では上限に達すると新規支出を保存できません。上限と同数のときに最も古い支出を削除して新規保存することに同意する場合だけ On にしてください。Owner の表示対象帳簿全体で、支出日、作成時刻、ID の順に古さを判定します。その特定の支出を削除する権限がなければ保存を拒否し、新しい記録に置き換えません。削除した支出は通常の支出取得、一覧、レポート、CSV に現れず、復元できません。内部監査履歴は保持し、権限のある直近 24 時間の操作ログには削除イベントと変更内容が表示される場合があります。プラン引き下げ後に上限を超えている場合は先に手動で整理してください。一括削除は行いません。保存失敗や同じ成功済みリクエストの再送で別の支出を削除することはありません。定期生成にも同じ設定が適用されます。 切り替え自体は支出を即時削除せず、使用量もリセットしません。",
        ko: "설정의 ‘가장 오래된 지출 자동 제거’는 모든 요금제에서 기본 Off이며 추가 요금이 없습니다. 다른 공유 장부를 선택해도 자신의 계정 설정을 변경하며 공유 장부는 자체 Owner 설정을 따릅니다. 지출 한도는 제거되지 않은 공유 풀 지출과 활성·보관된 프로젝트의 지출을 셉니다. 지출의 수동·자동 제거 또는 프로젝트 제거로 지출 자리가 비지만, 보관·제거된 프로젝트는 계속 프로젝트 한도를 사용합니다. Off이면 용량이 찼을 때 새 지출을 차단합니다. 정확히 한도에 도달했을 때 가장 오래된 지출을 제거한 뒤 새 지출을 저장하는 데 동의하는 경우에만 On으로 바꾸세요. 해당 Owner의 표시 대상 장부 전체에서 지출 날짜, 생성 시간, ID 순으로 판단합니다. 바로 그 지출을 제거할 권한이 없으면 저장을 차단하며 더 최근 기록으로 건너뛰지 않습니다. 제거한 지출은 일반 지출 조회·목록·보고서·CSV에서 사라지고 복원할 수 없습니다. 내부 감사 이력은 유지되며 권한이 있는 최근 24시간 작업 로그에는 제거 이벤트와 변경 내용이 표시될 수 있습니다. 요금제 하향 후 새 한도를 초과하면 먼저 수동 정리해야 하며 일괄 제거하지 않습니다. 저장 실패나 동일한 성공 요청 재전송은 다른 지출을 제거하지 않습니다. 반복 생성도 같은 설정을 따릅니다. 스위치를 바꾸는 것만으로 지출을 즉시 제거하거나 사용량을 초기화하지 않습니다.",
        fr: "Dans Paramètres, la suppression automatique de la dépense la plus ancienne est Off par défaut sur tous les plans, sans frais supplémentaires. Le réglage appartient à votre compte, même si un autre registre partagé est sélectionné ; chaque registre partagé suit celui de son Owner. La capacité compte les dépenses non supprimées du fonds partagé et des projets actifs ou archivés. Supprimer une dépense manuellement ou automatiquement, ou supprimer son projet, libère des places de dépenses ; les projets archivés et supprimés occupent toujours des places de projets. Off bloque les nouvelles dépenses lorsque la capacité est pleine. Activez On seulement si vous acceptez de supprimer la plus ancienne pour enregistrer une nouvelle dépense lorsque l’usage atteint exactement la limite. L’ordre est la date de dépense, puis la date de création, puis l’ID, dans tout le registre visible d’Owner. Sans autorisation de supprimer cette dépense précise, l’enregistrement est bloqué plutôt que de choisir une dépense plus récente. Les dépenses supprimées disparaissent des lectures ordinaires, listes, rapports et CSV, sans restauration possible. L’audit interne est conservé ; le journal autorisé des dernières 24 heures peut encore afficher les suppressions et leurs changements. Si un changement de plan laisse l’usage au-dessus de la limite, supprimez d’abord des dépenses manuellement ; aucun nettoyage en masse n’est effectué. Un échec ou une reprise de la même requête déjà réussie ne supprime pas d’autre dépense. La génération récurrente suit le même réglage. Changer le réglage ne supprime pas immédiatement de dépenses et ne réinitialise pas l’usage.",
        es: "En Ajustes, eliminar automáticamente el gasto más antiguo está Off por defecto en todos los planes, sin cargos adicionales. El ajuste pertenece a tu cuenta aunque selecciones otro libro compartido; cada libro compartido sigue el de su propio Owner. La capacidad cuenta gastos no eliminados del fondo compartido y de proyectos activos o archivados. Eliminar un gasto manual o automáticamente, o eliminar su proyecto, libera plazas de gastos; los proyectos archivados y eliminados siguen ocupando capacidad de proyectos. Off bloquea nuevos gastos cuando la capacidad está llena. Activa On solo si aceptas eliminar el más antiguo para guardar uno nuevo cuando el uso coincide exactamente con el límite. El orden es fecha del gasto, después fecha de creación y después ID, en todo el libro visible de Owner. Si no puedes eliminar ese gasto concreto, se bloquea el guardado en lugar de elegir uno más reciente. Los gastos eliminados desaparecen de consultas ordinarias, listas, informes y CSV, sin restauración posible. Se conserva la auditoría interna; el registro autorizado de las últimas 24 horas puede seguir mostrando eliminaciones y sus cambios. Si al reducir el plan el uso supera el límite, elimina gastos manualmente primero; no hay limpieza masiva. Un fallo o repetir la misma solicitud ya guardada no elimina otro gasto. La generación recurrente sigue el mismo ajuste. Cambiar el ajuste no elimina gastos inmediatamente ni reinicia el uso.",
      },
    ],
  },
};
