// One-shot codegen: transposes the two static phrase tables into per-locale
// modules so each locale ships only its own strings.
//
// Fidelity rule that must be preserved exactly (see T() in src/i18n.jsx):
//   EXTRA_PHRASE_TRANSLATIONS[en] || PHRASE_TRANSLATIONS[en]
// is an *object-level* choice. When a key exists in EXTRA, PHRASE is never
// consulted for that key, even for a locale that EXTRA does not translate.
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "src");
const LOCALES = ["zh", "ja", "ko", "fr", "es"];

const i18nText = fs.readFileSync(path.join(SRC, "i18n.jsx"), "utf8");
const lines = i18nText.split(/\r?\n/);
const start = lines.findIndex((l) => l.startsWith("const PHRASE_TRANSLATIONS = {"));
const end = lines.findIndex((l, i) => i > start && l === "};");
if (start < 0 || end < 0) throw new Error("could not locate PHRASE_TRANSLATIONS literal");
const phraseLiteral = lines.slice(start, end + 1).join("\n").replace(/^const /, "export const ");

const tmp = path.join(SRC, `__phrase-extract-${process.pid}.mjs`);
fs.writeFileSync(tmp, `/* eslint-disable no-dupe-keys */\n${phraseLiteral}\n`);
let PHRASE;
let EXTRA;
try {
  ({ PHRASE_TRANSLATIONS: PHRASE } = await import(pathToFileURL(tmp).href));
  ({ EXTRA_PHRASE_TRANSLATIONS: EXTRA } = await import(
    pathToFileURL(path.join(SRC, "i18n-extra.js")).href
  ));
} finally {
  fs.rmSync(tmp, { force: true });
}

const keys = [...new Set([...Object.keys(EXTRA), ...Object.keys(PHRASE)])];
const outDir = path.join(SRC, "locales");
fs.mkdirSync(outDir, { recursive: true });

const summary = [];
for (const locale of LOCALES) {
  const table = {};
  for (const en of keys) {
    const source = Object.hasOwn(EXTRA, en) ? EXTRA[en] : PHRASE[en];
    const value = source?.[locale];
    if (typeof value === "string" && value !== "") table[en] = value;
  }
  const body = Object.entries(table)
    .map(([en, v]) => `  ${JSON.stringify(en)}: ${JSON.stringify(v)},`)
    .join("\n");
  const file = path.join(outDir, `${locale}.js`);
  fs.writeFileSync(
    file,
    `// Generated by scripts/split-locales.mjs — do not edit by hand.\n` +
      `export const PHRASES = {\n${body}\n};\n`
  );
  summary.push([locale, Object.keys(table).length, fs.statSync(file).size]);
}

console.log(`keys: ${keys.length} (EXTRA ${Object.keys(EXTRA).length}, PHRASE ${Object.keys(PHRASE).length})`);
for (const [locale, n, bytes] of summary) {
  console.log(`  ${locale}: ${String(n).padStart(4)} phrases  ${(bytes / 1024).toFixed(1).padStart(6)} kB`);
}
