// data.jsx — fixture data for the prototype
export const REPOS = [
  { id: "r1", name: "vercel/next.js", desc: "The React Framework for the Web", lang: "TypeScript", stars: "121k", updated: "2 hours ago", private: false, branches: 24, default: "canary" },
  { id: "r2", name: "linear/desktop", desc: "Linear desktop app — issue tracking and project management", lang: "TypeScript", stars: "—", updated: "yesterday", private: true, branches: 18, default: "main" },
  { id: "r3", name: "supabase/supabase", desc: "The open source Firebase alternative", lang: "TypeScript", stars: "73.4k", updated: "1 day ago", private: false, branches: 12, default: "master" },
  { id: "r4", name: "tldraw/tldraw", desc: "Whiteboard SDK / infinite canvas", lang: "TypeScript", stars: "33.7k", updated: "3 days ago", private: false, branches: 6, default: "main" },
  { id: "r5", name: "raycast/extensions", desc: "Everything you need to extend Raycast", lang: "TypeScript", stars: "5.8k", updated: "5 hours ago", private: false, branches: 9, default: "main" },
  { id: "r6", name: "yourname/billing-service", desc: "Internal billing & invoicing service", lang: "Go", stars: "—", updated: "an hour ago", private: true, branches: 31, default: "main" },
  { id: "r7", name: "yourname/portfolio-2025", desc: "Personal site, redesigned", lang: "TypeScript", stars: "—", updated: "4 days ago", private: true, branches: 3, default: "main" },
  { id: "r8", name: "yourname/dotfiles", desc: "Shell, editor, and tooling configs", lang: "Shell", stars: "—", updated: "2 weeks ago", private: true, branches: 1, default: "main" },
];

// 6 issues categories — security, quality, performance, deps, tests, docs
export const ISSUES = [
  {
    id: "PR-001", severity: "critical", category: "Security",
    title: "硬编码的 API 密钥泄露在前端 bundle",
    file: "apps/web/src/lib/payments.ts", line: 14,
    summary: "Stripe secret key 直接写在客户端代码中, 构建后会暴露给所有访问者。",
    impact: "任何用户可读取 bundle 提取密钥, 存在严重资金风险。",
    status: "open", confidence: 0.97, effort: "5 min", autoFix: true,
    tags: ["secrets", "stripe", "client-side"],
    age: "刚发现",
    badCode: [
      { ln: 12, code: "// Initialize payments client" },
      { ln: 13, code: "import Stripe from \"stripe\";", t: "del" },
      { ln: 14, code: "export const stripe = new Stripe(\"sk_live_51N...4dQp\");", t: "del" },
      { ln: 15, code: "" },
    ],
    goodCode: [
      { ln: 12, code: "// Initialize payments client (server-only)" },
      { ln: 13, code: "import Stripe from \"stripe\";", t: "add" },
      { ln: 14, code: "if (typeof window !== \"undefined\")", t: "add" },
      { ln: 15, code: "  throw new Error(\"stripe must not be used on the client\");", t: "add" },
      { ln: 16, code: "export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);", t: "add" },
    ],
    steps: [
      "将 stripe 实例移动到 server-only 模块, 添加 \"server-only\" 包导入。",
      "把 sk_live_… 写入 .env.local 与部署环境变量, 立刻在 Stripe Dashboard 撤销旧 key。",
      "改用 process.env.STRIPE_SECRET_KEY 读取, 避免在客户端构建时被打包。",
      "在 CI 中加入 secret scanning(gitleaks)预防回归。",
    ],
    references: [
      { label: "Stripe — Securing your secret keys", url: "stripe.com/docs/keys" },
      { label: "Next.js — Server-only modules", url: "nextjs.org/docs/app/building-your-application/rendering/composition-patterns" }
    ],
  },
  {
    id: "PR-002", severity: "critical", category: "Security",
    title: "SQL 字符串拼接导致注入风险",
    file: "apps/api/src/routes/search.ts", line: 42,
    summary: "用户输入直接拼入 SQL 查询, 未使用参数化查询。",
    impact: "攻击者可读取或破坏整个数据库。",
    status: "open", confidence: 0.94, effort: "8 min", autoFix: true,
    tags: ["sql-injection", "owasp-a03"],
    age: "刚发现",
    badCode: [
      { ln: 40, code: "router.get(\"/search\", async (req, res) => {" },
      { ln: 41, code: "  const { q } = req.query;" },
      { ln: 42, code: "  const rows = await db.raw(`SELECT * FROM items WHERE name LIKE '%${q}%'`);", t: "del" },
      { ln: 43, code: "  res.json(rows);" },
    ],
    goodCode: [
      { ln: 40, code: "router.get(\"/search\", async (req, res) => {" },
      { ln: 41, code: "  const { q } = req.query;" },
      { ln: 42, code: "  const rows = await db(\"items\")", t: "add" },
      { ln: 43, code: "    .where(\"name\", \"like\", `%${q}%`)", t: "add" },
      { ln: 44, code: "    .select(\"*\");", t: "add" },
      { ln: 45, code: "  res.json(rows);" },
    ],
    steps: [
      "使用 query builder 的参数化绑定, 避免手动拼接 SQL。",
      "在请求层使用 zod 校验 q 长度与字符集。",
      "为 items.name 字段建立 trigram 索引以保证模糊查询性能。",
    ],
    references: [
      { label: "OWASP — SQL Injection Prevention", url: "owasp.org/www-community/attacks/SQL_Injection" }
    ],
  },
  {
    id: "PR-003", severity: "high", category: "Performance",
    title: "Dashboard 组件触发 N+1 数据获取",
    file: "apps/web/src/app/(dashboard)/page.tsx", line: 88,
    summary: "对每个 project 单独发起 fetch — 100 个项目时产生 100 次请求。",
    impact: "首屏加载从 320ms 增加到 3.4s; FID 远超阈值。",
    status: "open", confidence: 0.89, effort: "12 min", autoFix: true,
    tags: ["n+1", "react-query", "data-fetching"],
    age: "2 天前",
    steps: [
      "把每行 fetch 合并成一次 GET /projects/stats?ids=…",
      "在 React Query 中使用 useQueries + 批量 endpoint。",
      "添加 60s 的 staleTime 减少切换页签时的重复请求。",
    ],
    references: [{ label: "TanStack Query — useQueries", url: "tanstack.com/query/v5" }],
  },
  {
    id: "PR-004", severity: "high", category: "Dependencies",
    title: "axios@0.21.1 存在 SSRF 漏洞 (CVE-2023-45857)",
    file: "package.json", line: 28,
    summary: "当前版本受 CVE-2023-45857 影响, 已有可用补丁。",
    impact: "受影响版本: <1.6.0; 攻击者可构造 URL 触发 SSRF。",
    status: "open", confidence: 1.0, effort: "1 min", autoFix: true,
    tags: ["cve", "npm", "supply-chain"],
    age: "1 周前",
    steps: ["升级到 axios@^1.6.7", "运行 pnpm dedupe 移除幽灵依赖", "在 CI 集成 osv-scanner"],
    references: [{ label: "CVE-2023-45857", url: "nvd.nist.gov/vuln/detail/CVE-2023-45857" }],
  },
  {
    id: "PR-005", severity: "medium", category: "Quality",
    title: "useEffect 依赖数组缺失引发陈旧闭包",
    file: "apps/web/src/components/Editor.tsx", line: 137,
    summary: "依赖项 onSave 未声明, 触发保存时使用过期的 props。",
    impact: "用户保存时偶发提交旧数据。",
    status: "open", confidence: 0.82, effort: "3 min", autoFix: true,
    tags: ["react-hooks", "stale-closure"],
    age: "3 天前",
    steps: ["在依赖数组里加入 onSave", "使用 useEvent 抽象避免不必要的重渲染"],
    references: [{ label: "React docs — exhaustive-deps", url: "react.dev/learn/synchronizing-with-effects" }],
  },
  {
    id: "PR-006", severity: "medium", category: "Quality",
    title: "重复实现的日期格式化函数",
    file: "packages/utils/format.ts", line: 1,
    summary: "在 4 个文件中分别实现了几乎相同的 formatDate, 行为存在分歧。",
    impact: "i18n 不一致; 时区处理差异导致 bug。",
    status: "snoozed", confidence: 0.75, effort: "20 min", autoFix: false,
    tags: ["duplication", "refactor"],
    age: "5 天前",
    steps: ["统一为 packages/utils/date.ts 中的 formatRelative", "替换其他 3 处实现", "添加 luxon 处理时区"],
  },
  {
    id: "PR-007", severity: "medium", category: "Tests",
    title: "Payments 模块测试覆盖率 32% — 低于阈值 70%",
    file: "apps/api/src/payments/", line: 0,
    summary: "核心计费路径无单元测试, 仅依赖手动 QA。",
    impact: "金额计算边界条件未覆盖, 上线风险高。",
    status: "open", confidence: 1.0, effort: "—", autoFix: false,
    tags: ["coverage", "vitest"],
    age: "1 天前",
    steps: ["补充 calculateTax / applyCoupon 的属性测试", "为 webhook 重试逻辑写集成测试"],
  },
  {
    id: "PR-008", severity: "low", category: "Performance",
    title: "图片未指定 width/height 引发布局位移",
    file: "apps/web/src/app/blog/[slug]/page.tsx", line: 54,
    summary: "next/image 缺少显式尺寸, 触发 CLS 0.21。",
    impact: "Core Web Vitals 评分降级。",
    status: "open", confidence: 0.91, effort: "4 min", autoFix: true,
    tags: ["cls", "core-web-vitals"], age: "2 天前",
    steps: ["读取图片元数据并传入 width/height", "在 markdown 处理器中自动注入"],
  },
  {
    id: "PR-009", severity: "low", category: "Docs",
    title: "README 中 5 个 API 示例已过期",
    file: "README.md", line: 102,
    summary: "示例使用 v1 endpoints, 当前版本为 v3。",
    impact: "新接入的开发者按文档跑会失败。",
    status: "open", confidence: 0.7, effort: "10 min", autoFix: false,
    tags: ["docs"], age: "1 周前",
    steps: ["更新所有 endpoint 至 v3", "使用 doctest 自动校验示例"],
  },
  {
    id: "PR-010", severity: "low", category: "Quality",
    title: "console.log 留存在生产代码 (12 处)",
    file: "—", line: 0,
    summary: "12 个文件中存在调试用 console.log。",
    impact: "信息泄露风险, 影响 logging 性能。",
    status: "fixed", confidence: 1.0, effort: "2 min", autoFix: true,
    tags: ["lint", "no-console"], age: "已修复",
    steps: ["统一替换为 logger.debug", "ESLint 规则 no-console 设为 error"],
  },
  {
    id: "PR-011", severity: "info", category: "Architecture",
    title: "建议拆分 monolithic API gateway",
    file: "apps/api/", line: 0,
    summary: "gateway 文件夹下混合了 auth、payments、analytics 三个领域的逻辑。",
    impact: "团队并行开发时合并冲突频繁。",
    status: "open", confidence: 0.65, effort: "—", autoFix: false,
    tags: ["architecture", "advisory"], age: "新建议",
    steps: ["按领域拆分包: @api/auth, @api/payments, @api/analytics", "保留同一进程, 仅改包结构"],
  },
];

// History
export const SCANS = [
  { id: "s1", repo: "yourname/billing-service", time: "刚刚", status: "running", branch: "main", commit: "a3f9c2", issues: null, by: "auto" },
  { id: "s2", repo: "yourname/billing-service", time: "今天 09:14", status: "done", branch: "main", commit: "f08d11", issues: { critical: 2, high: 4, medium: 9, low: 7 }, by: "you" },
  { id: "s3", repo: "yourname/portfolio-2025", time: "昨天 16:22", status: "done", branch: "feat/redesign", commit: "1c4e8b", issues: { critical: 0, high: 1, medium: 3, low: 5 }, by: "you" },
  { id: "s4", repo: "linear/desktop", time: "2 天前", status: "done", branch: "main", commit: "9b2a30", issues: { critical: 1, high: 3, medium: 12, low: 14 }, by: "auto" },
  { id: "s5", repo: "yourname/billing-service", time: "3 天前", status: "done", branch: "fix/webhook", commit: "5d7e91", issues: { critical: 0, high: 2, medium: 4, low: 3 }, by: "you" },
  { id: "s6", repo: "yourname/dotfiles", time: "上周", status: "failed", branch: "main", commit: "—", issues: null, by: "you" },
];

// Sparkline data — issues found over last 14 days
export const TREND = [12, 8, 14, 9, 11, 6, 10, 7, 5, 8, 4, 6, 3, 4];

export const FIXTURES = { REPOS, ISSUES, SCANS, TREND };
